main: com.winthier.stoprain.StopRainPlugin
name: StopRain

version: 0.1
api-version: 1.19

description: Stop the rain
author: StarTux
website: https://cavetale.com

commands:

  endrain:
    aliases: [ stoprain, norain ]
    description: Stop the rain on your client
    usage: /<command> [on|off]

permissions: {}
